### PR TITLE
Added rspec_rails gem, factory_girl_rails gem, removed test folder, codeship 

### PR DESCRIPTION
**Pull request by digisora**
- Added a simple test add_spec.rb to make sure rspec is working. 
- Rspec plus factory girl was the simple choice since we are all familiar with it, let me know if you prefer something else.
- Decided on codeship based on my mentor's recommendation.

### CODE REVIEW

**Comment by cchoi12** [comment]
Took a look and am not sure why the Gemfile has a conflict, not familiar with the formatting.

**Comment by digisora** [comment]
Hrm I'm not sure what the conflict is

**Comment by cmaddox5** [comment]
I think the problem comes from your Gemfile not having the changes that Chris added when he merged his pull request. Your additions to the Gemfile start on line 41. After Chris's pull request, the last line of the Gemfile should be line 46. 

What you might try doing is redo your Gemfile after copying the Gemfile that is in master currently. This should line up the additions and make it easier for Github to merge. After you add your stuff on top of the master version, run bundle install and the .lock should merge better too.

**Comment by digisora** [comment]
Updated branch from master, conflicts with gemfile and gemfile.lock should now be resolved.

**Comment by cmaddox5** [comment]
Looks good to me.

**Comment by Ryomablue** [comment]
Also looks good to me.

**Pull request merged**
